services:
  pocketbase:
    build:
      context: .
      args:
        PB_VERSION: 0.28.1
    container_name: pocketbase-app
    environment:
      - PB_PORT=8090
    ports:
      - "8090:8090"      
    # volumes:
    #   - ./pb_data:/pb/pb_data
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui